# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_auto_20171028_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touroffering',
            name='user',
        ),
    ]
