# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0004_auto_20171028_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroffering',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
