# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0005_auto_20171028_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
