# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0006_booking_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=None, verbose_name='login date'),
        ),
    ]
