# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0007_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='price',
            new_name='weekday_price',
        ),
        migrations.AddField(
            model_name='tour',
            name='weekend_price',
            field=models.IntegerField(default=0),
        ),
    ]
