# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import line.models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0009_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='elder_num',
            new_name='toolder_num',
        ),
        migrations.AlterField(
            model_name='touroffering',
            name='offer_date',
            field=models.DateTimeField(default=line.models.TourOffering.default_offer_time, verbose_name='offer date'),
        ),
    ]
