# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0013_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='question',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
