# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0014_auto_20171029_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=20)),
                ('question', models.ManyToManyField(to='line.Faq')),
            ],
        ),
    ]
