# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0016_auto_20171029_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='faq',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
