# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0018_auto_20171029_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.User')),
            ],
        ),
    ]
