# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0019_userchoose'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroffering',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
