# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0021_auto_20171029_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
            ],
        ),
    ]
