# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0022_unknownquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='toolder_num',
            new_name='toddler_num',
        ),
    ]
