# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0023_auto_20171029_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adult_num',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='toddler_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
