# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0025_auto_20171029_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='travel_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
