# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0026_user_travel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownquestion',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
