# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0029_auto_20171111_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='pushed',
            field=models.BooleanField(default=False),
        ),
    ]
