# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0030_discount_pushed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='img_path',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_description',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='line.Discount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.IntegerField(choices=[(1, 'CONFIRMED'), (0, 'IS_BOOKING'), (2, 'PAID')], default=0),
        ),
        migrations.AlterField(
            model_name='touroffering',
            name='state',
            field=models.IntegerField(choices=[(2, 'CANCELED'), (3, 'CLOSED'), (1, 'CONFIRMED'), (0, 'OPEN')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='travel_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
